### PR TITLE
added web/favicon.png and web/images/favicon.svg (template)

### PR DESCRIPTION
**Pull request by ghost**
16 x 16 px version of the agreed-upon favicon as PNG.
That's the pixel-aligned one (better recognition factor).
Includes the developer variant of the SVG template, too.
I can also add a favicon.ico in case we really need one.

### CODE REVIEW

**Comment by MichaelKohler** [comment]
Hi Marco, thanks for the PR, a couple of notes:

1) Could you upload the svg without the grid so we can use it as svg favicon as well?
2) Could you upload it to the mozilla_branding repo as well?

Thanks a lot!

**Comment by MichaelKohler** [comment]
could you please also replace the apple-touch-icon.png with that? and the favicon.ico once we're at it :)

also, could you put the svg in the web/ folder directly as well?

I know, a lot of requests, sorry about that ;)

**Comment by ghost** [comment]
No problem. I'll see to that.
I suppose I'll have to create a new pull request for that, right?
Is the correct way to cancel an existing one to simply close it?

**Comment by MichaelKohler** [comment]
You can just update your current branch and the PR will be updated. We don't necessarily need one commit per PR, so that works :)

**Comment by ghost** [comment]
The apple-touch-icon should contain the nice avatar image, right?
(Its resolution is much better than 16x16, after all.)

**Comment by MichaelKohler** [comment]
sure :)

**Comment by ghost** [comment]
CI (Travis) may have a problem with the container (docker) configuration. The last run failed.

<pre>
...
1973) Step 17 : CMD /opt/start.sh
1974)  ---> Running in 026a04595ffd
1975)  ---> 6be22b3d2b1b
1976) Removing intermediate container 026a04595ffd
1977) Successfully built 6be22b3d2b1b
1978)
1979) $ docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
1980) Password: 
1981)
1982) No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
1983) 
1984) The build has been terminated
1985)
</pre>

**Comment by freaktechnik** [comment]
That might just be a hickup, but it's not in the actual test part so it... shouldn't matter.
Actually, for pulls the env vars aren't set, sooo yup.

**Comment by freaktechnik** [comment]
Thanks for the nice work!

**Pull request merged**
