### PR TITLE
use official unicode symbols

### PR DESCRIPTION
**Pull request by J0WI**
I removed the images and custom font icon in favour of the official Unicode symbols. Merge if you agree.

### CODE REVIEW

**Comment by freaktechnik** [comment]
Mozilla uses \f073 for the calendar in their font, if I read home.less correctly.

**Comment by J0WI** [comment]
That's the 'private use area' of Unicode. The official calender symbol would be one of the following:
\1F4C5 \1F4C6 \1F5D3
(📅 📆 🗓)

**Comment by freaktechnik** [comment]
Sure, but why would we use a different calendar glyph than the one the font provides by default?
EDIT: especially since we already have that symbol once in the next event tile, which uses the mozilla styles.

**Comment by J0WI** [comment]
I think it would be better for semantics (e.g. screen reader or search engines).
How do you think about replacing the images?

**Comment by freaktechnik** [comment]
I don't think using the correct glyph for a decorational calendar icon is needed. That said, I also have no idea hiw screen readers read non-characters.

Concerning the other replacements: I haven't looked at the result yet.
EDIT: tried your pull, and it seems my firefox doesn't know of a font that has the group or the envelope icon. So that's not good. I think we should stick to what's integrated in the FA-Icons font, since those will work on all possible configurations.
EDIT2: screenshot from 2015-04-03 18 22 47 Please also not the two different calendar icons used here, due to one being from FA-Icons and the other one from whatever font Firefox found with the icon.

**Comment by J0WI** [comment]
Okay, loading an additional font that supports these Unicode characters would be less fast that SVG.

**Pull request closed without merging**
